import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
INK = colors.HexColor('#190019')
PLUM = colors.HexColor('#522B5B')
MAUVE = colors.HexColor('#854F6C')
CREAM = colors.HexColor('#FBE4D8')

def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle('ReportTitle', parent=ss['Title'], textColor=INK, fontSize=20, spaceAfter=4))
    ss.add(ParagraphStyle('ReportSub', parent=ss['Normal'], textColor=MAUVE, fontSize=10, spaceAfter=14))
    ss.add(ParagraphStyle('VerdictBig', parent=ss['Title'], textColor=PLUM, fontSize=32, alignment=1))
    ss.add(ParagraphStyle('VerdictSmall', parent=ss['Normal'], textColor=MAUVE, fontSize=11, alignment=1, spaceAfter=16))
    ss.add(ParagraphStyle('CheckLabel', parent=ss['Normal'], textColor=INK, fontSize=11, fontName='Helvetica-Bold'))
    ss.add(ParagraphStyle('CheckDetail', parent=ss['Normal'], textColor=colors.HexColor('#3a2340'), fontSize=9, leading=12))
    ss.add(ParagraphStyle('Disclaimer', parent=ss['Normal'], textColor=colors.grey, fontSize=8, spaceBefore=18))
    return ss

def generate_pdf_report(title: str, confidence_pct: float, verdict: str, checks: list, image_bytes: bytes=None, source_label: str='') -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER, topMargin=0.6 * inch, bottomMargin=0.6 * inch, leftMargin=0.7 * inch, rightMargin=0.7 * inch)
    styles = _styles()
    story = []
    story.append(Paragraph(title, styles['ReportTitle']))
    generated = datetime.now().strftime('%B %d, %Y at %H:%M')
    sub = f'Generated {generated}'
    if source_label:
        sub += f' · {source_label}'
    story.append(Paragraph(sub, styles['ReportSub']))
    if image_bytes:
        try:
            img_buf = io.BytesIO(image_bytes)
            rl_img = RLImage(img_buf, width=2.2 * inch, height=2.2 * inch, kind='proportional')
            story.append(rl_img)
            story.append(Spacer(1, 12))
        except Exception:
            pass
    story.append(Paragraph(f'{confidence_pct:.0f}%', styles['VerdictBig']))
    story.append(Paragraph(verdict, styles['VerdictSmall']))
    rows = []
    for check in checks:
        status = 'FLAGGED' if check.get('flagged') else 'CLEAR'
        rows.append([Paragraph(f"{check.get('label', '')}<br/><font size=9 color='#3a2340'>{check.get('detail', '')}</font>", styles['CheckDetail']), status])
    table = Table(rows, colWidths=[5.3 * inch, 1.0 * inch])
    table.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'TOP'), ('BOTTOMPADDING', (0, 0), (-1, -1), 10), ('TOPPADDING', (0, 0), (-1, -1), 10), ('LINEBELOW', (0, 0), (-1, -1), 0.5, colors.HexColor('#e0d0d8')), ('FONTNAME', (1, 0), (1, -1), 'Helvetica-Bold'), ('FONTSIZE', (1, 0), (1, -1), 9), ('TEXTCOLOR', (1, 0), (1, -1), PLUM), ('ALIGN', (1, 0), (1, -1), 'RIGHT')]))
    story.append(table)
    story.append(Paragraph('This report is generated by automated heuristic and model-based checks. No detector is infallible - treat this as a strong signal to weigh, not a guaranteed verdict, especially for anything where the answer actually matters (a dispute, an accusation, a news story). Where noted, some checks are offline estimates rather than trained-model results.', styles['Disclaimer']))
    doc.build(story)
    return buf.getvalue()

def report_from_dict(report: dict, title: str, check_keys: list, image_bytes: bytes=None, source_label: str='') -> bytes:
    confidence_pct = report.get('confidence_pct', report.get('risk_pct', 0.0))
    verdict = report.get('verdict', '')
    checks = [report[k] for k in check_keys if k in report and isinstance(report[k], dict)]
    return generate_pdf_report(title, confidence_pct, verdict, checks, image_bytes=image_bytes, source_label=source_label)
